package com.adri1711.util.enums;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public enum XMaterial {
    AIR, ANVIL, ARROW, BEDROCK, BEEF,
    BLACK_TERRACOTTA, BLAZE_ROD, BLUE_TERRACOTTA, BOW, BROWN_TERRACOTTA,
    CHEST, CHIPPED_ANVIL, COAL_BLOCK, COOKED_BEEF, COOKED_PORKCHOP,
    DAMAGED_ANVIL, DIAMOND_HOE, DIAMOND_SHOVEL, DIRT, EGG,
    EMERALD, EMERALD_BLOCK, ENDER_EYE, GLASS, GOLDEN_HELMET,
    GOLDEN_HOE, GOLDEN_SHOVEL, GOLDEN_SWORD, GRAY_TERRACOTTA, GREEN_TERRACOTTA,
    IRON_BOOTS, IRON_HOE, IRON_HORSE_ARMOR, IRON_SHOVEL, IRON_SWORD,
    LEATHER_CHESTPLATE, MAP, NETHER_STAR, OAK_BOAT, OAK_SIGN,
    ORANGE_DYE, PURPLE_TERRACOTTA, REDSTONE_BLOCK, RED_DYE, RED_TERRACOTTA,
    SADDLE, SKELETON_SKULL, SNOW, SNOWBALL, STONE,
    STONE_HOE, STONE_PRESSURE_PLATE, STONE_SHOVEL, STONE_SWORD, TNT,
    TOTEM_OF_UNDYING, TROPICAL_FISH, WATER, WATER_BUCKET, WHITE_STAINED_GLASS,
    WHITE_STAINED_GLASS_PANE, WHITE_TERRACOTTA, WOODEN_HOE, WOODEN_SHOVEL, WOODEN_SWORD,
    YELLOW_TERRACOTTA, BLACK_WOOL, BLUE_WOOL, BROWN_WOOL, GRAY_WOOL,
    GREEN_WOOL, PURPLE_WOOL, RED_WOOL, YELLOW_WOOL,
    TINTED_GLASS, BLACK_STAINED_GLASS, BLUE_STAINED_GLASS, BROWN_STAINED_GLASS,
    CYAN_STAINED_GLASS, GRAY_STAINED_GLASS, GREEN_STAINED_GLASS,
    LIGHT_BLUE_STAINED_GLASS, LIGHT_GRAY_STAINED_GLASS, LIME_STAINED_GLASS,
    MAGENTA_STAINED_GLASS, ORANGE_STAINED_GLASS, PINK_STAINED_GLASS,
    PURPLE_STAINED_GLASS, RED_STAINED_GLASS, YELLOW_STAINED_GLASS;

    public ItemStack parseItem(){
        Material mat;
        try{ mat = Material.valueOf(name()); }catch(Exception ex){ mat = Material.AIR; }
        return new ItemStack(mat);
    }
    public Material parseMaterial(){
        try{ return Material.valueOf(name()); }catch(Exception ex){ return Material.AIR; }
    }
    public byte getData(){ return 0; }
    public static XMaterial matchXMaterial(Material mat){
        try{ return valueOf(mat.name()); }catch(Exception ex){ return AIR; }
    }
}
