package com.adri1711.util.enums;

import org.bukkit.Sound;

public enum XSound {
    BLOCK_ANVIL_BREAK("BLOCK_ANVIL_BREAK"),
    BLOCK_GLASS_BREAK("BLOCK_GLASS_BREAK"),
    BLOCK_NOTE_BLOCK_BANJO("BLOCK_NOTE_BLOCK_BANJO"),
    BLOCK_WOODEN_DOOR_CLOSE("BLOCK_WOODEN_DOOR_CLOSE"),
    ENTITY_BAT_HURT("ENTITY_BAT_HURT"),
    ENTITY_ENDERMAN_TELEPORT("ENTITY_ENDERMAN_TELEPORT"),
    ENTITY_ENDER_DRAGON_DEATH("ENTITY_ENDER_DRAGON_DEATH"),
    ENTITY_ENDER_DRAGON_GROWL("ENTITY_ENDER_DRAGON_GROWL"),
    ENTITY_GENERIC_EXPLODE("ENTITY_GENERIC_EXPLODE"),
    ENTITY_PLAYER_LEVELUP("ENTITY_PLAYER_LEVELUP"),
    ENTITY_VILLAGER_DEATH("ENTITY_VILLAGER_DEATH"),
    ENTITY_VILLAGER_HURT("ENTITY_VILLAGER_HURT"),
    ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR("ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR"),
    ITEM_TOTEM_USE("ITEM_TOTEM_USE");

    private final Sound sound;
    XSound(String name){
        Sound s;
        try{ s = Sound.valueOf(name); } catch(Exception ex){ s = Sound.BLOCK_NOTE_BLOCK_BASS; }
        this.sound = s;
    }
    public Sound parseSound(){ return sound; }
}
